server:
  port: 8080
  servlet:
    context-path: /api/v1
access_token:
  key: ${ACCESS_TOKEN_PRIVATE_KEY}
  expiry: ${ACCESS_TOKEN_EXPIRATION_TIME_MS}
refresh_token:
  key: ${REFRESH_TOKEN_PRIVATE_KEY}
  expiry: ${REFRESH_TOKEN_EXPIRATION_TIME_MS}

logging:
  level:
    org.springframework.security: TRACE
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_SERVER_USERNAME}
    password: ${MAIL_SERVER_PASSSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

