server:
  port: 8080
  servlet:
    context-path: /api/v1

logging:
  level:
    org.springframework.security: TRACE

access-token:
  private: ${ACCESS_TOKEN_PRIVATE_KEY}
  public: ${ACCESS_TOKEN_PUBLIC_KEY}
refresh-token:
  private: ${REFRESH_TOKEN_PRIVATE_KEY}
  public: ${REFRESH_TOKEN_PUBLIC_KEY}

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 47894533207-pe87eel07em75s1s9p8v5qlojho31gc8.apps.googleusercontent.com
#            client-secret: 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
      resourceserver:
        jwt:
          issuer-uri: https://my-auth-server.com